services:
  parking_api_dev:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  parking_api:
    tty: true
    build:
      args:
        - RAILS_ENV=production
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres13:/var/lib/postgresql/data

volumes:
  postgres13:
