default: &default
  adapter: postgresql
  enconding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'postgres') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  locale: pt_BR.UTF-8

development:
  <<: *default
  database: parking_api_development

test:
  <<: *default
  database: parking_api_test

production:
  <<: *default
  database: parking_api_production
